#!/usr/bin/env bash
# KuaiRec DARLR 单次训练入口。完整阶段实验请使用
# script/run_DARLR_KuaiRec_pipeline.sh。
set -euo pipefail

cd "$(dirname "$0")/.."

export DATASET="KuaiEnv-v0"

export SEED="${SEED:-2023}"
export CUDA="${CUDA:-1}"
export EPOCH="${EPOCH:-100}"
export STEP_PER_EPOCH="${STEP_PER_EPOCH:-100000}"
export TRAINING_NUM="${TRAINING_NUM:-100}"
export TEST_NUM="${TEST_NUM:-100}"
export BATCH_SIZE="${BATCH_SIZE:-256}"

export WHICH_TRACKER="${WHICH_TRACKER:-sasrec}"
export WINDOW_SIZE="${WINDOW_SIZE:-3}"
export NUM_HEADS="${NUM_HEADS:-1}"

# 论文 KuaiRec 协议 N=4, M=0：当前实现对应“前 3 个 + 当前动作”。
export MAX_TURN="${MAX_TURN:-30}"
export FORCE_LENGTH="${FORCE_LENGTH:-10}"
export NUM_LEAVE_COMPUTE="${NUM_LEAVE_COMPUTE:-3}"
export LEAVE_THRESHOLD="${LEAVE_THRESHOLD:-0}"

export SELECTOR_K="${SELECTOR_K:-10}"
export SELECTOR_CANDIDATE_SIZE="${SELECTOR_CANDIDATE_SIZE:-512}"
export SELECTOR_CANDIDATE_MODE="${SELECTOR_CANDIDATE_MODE:-embedding_topk}"
export SELECTOR_POLICY_MODE="${SELECTOR_POLICY_MODE:-learned}"
export SELECTOR_PREF_DIM="${SELECTOR_PREF_DIM:-64}"
export SELECTOR_NUM_HEADS="${SELECTOR_NUM_HEADS:-1}"
export SELECTOR_NUM_LAYERS="${SELECTOR_NUM_LAYERS:-1}"
export SELECTOR_LAMBDA_S="${SELECTOR_LAMBDA_S:-1.0}"
export SELECTOR_LAMBDA_D="${SELECTOR_LAMBDA_D:-0.05}"

export SELECTOR_LR="${SELECTOR_LR:-0.0003}"
export SELECTOR_ENT_COEF="${SELECTOR_ENT_COEF:-0.001}"
export SELECTOR_ADVANTAGE_NORMALIZATION="${SELECTOR_ADVANTAGE_NORMALIZATION:-1}"
export SELECTOR_REWARD_NORMALIZATION="${SELECTOR_REWARD_NORMALIZATION:-0}"
export SELECTOR_NORMALIZATION_EPS="${SELECTOR_NORMALIZATION_EPS:-1.0e-8}"
export MAX_GRAD_NORM="${MAX_GRAD_NORM-5.0}"
export REW_NORM="${REW_NORM:-0}"

export SELECTOR_REWARD_MODE="${SELECTOR_REWARD_MODE:-full}"
export DYNAMIC_REWARD_MODE="${DYNAMIC_REWARD_MODE:-reference_mean}"
export DYNAMIC_UNCERTAINTY_MODE="${DYNAMIC_UNCERTAINTY_MODE:-dynamic}"
export LAMBDA_UNCERTAINTY="${LAMBDA_UNCERTAINTY:-0.05}"
export LAMBDA_ENTROPY="${LAMBDA_ENTROPY:-0.05}"
export LAMBDA_VARIANCE="${LAMBDA_VARIANCE:-0.0}"

export BEST_METRIC="${BEST_METRIC:-NX_0}"
# 默认只保存一个按 NX_0 选出的最优 checkpoint，避免逐 epoch 占满磁盘。
export SAVE_MODEL="${SAVE_MODEL:-1}"
export SAVE_BEST_ONLY="${SAVE_BEST_ONLY:-1}"
export DRY_RUN="${DRY_RUN:-0}"

export MESSAGE="${MESSAGE:-DARLR_KuaiRec_full_seed${SEED}}"
export READ_MESSAGE="${READ_MESSAGE:-pointneg}"

exec bash script/run_DARLR_reproduce.sh "$@"
